### PR TITLE
Added Edge version 12 & 13 detection

### PR DESCRIPTION
**Pull request by notacouch**
Also bumped the version's minor revision #.

### CODE REVIEW

**Comment by stowball** [comment]
Hmmm. I haven't been testing for different versions in other evergreen browsers, so not sure I want to start now - unless previous versions of Edge had obvious bugs?

Also, if I were to test, I'd continue to test for CSS properties, as opposed to creating an element, which is much slower

**Comment by notacouch** [comment]
Hrm. All good points. I can't even remember why I set out to distinguish the versions. I'll be sure to add here if I can recall.

That's the first I'm hearing that creating an element is much slower. I imagine it _is_, but I can't imagine that difference being significant in terms of the user's experience. Not trying to argue here, am just curious, would appreciate it if you've any articles or tests I could learn from. 

More importantly -- do you have any advice on how to find what CSS properties to test for? I've just been going through their changelogs which is a bit of a pain.

Thanks.

**Comment by notacouch** [comment]
Side note, would you consider adding something like `vendor-ms`, some sort of reference if we want to style for a Microsoft browser whether it's IE or Edge? E.g. I have been using SVGs, IE10+ and Edge seem to have the same support. Transforms can work via attributes, but not via CSS, nevermind transitions/animations. So once I started supporting Edge I found myself needing something like `vendor-ms` so it's not so much IE or Edge that I'm targeting, but either.

**Comment by stowball** [comment]
Not sure how I missed your replies 😕

I use http://mattstow.com/experiment/layout-engine/style.html to list out all the style properties on `<html>`, then use Beyond Compare to see which properties were added and removed in each release.

As for your `.vendor-ms` request, again, I don't want to lump Edge as an evergreen browser in with bad, old IE as I hope it will quickly shake off any shackles of IE's past.

You can always use both `.vendor-ie` and `.vendor-edge` to target things in your CSS:

```scss
.vendor-ie, .vendor-edge {
  svg {
    fill: blue;
  }
}
```

**Pull request closed without merging**
